check bash

diff --git a/cicd/templates/steps-deploy-amazon-q.yaml b/cicd/templates/steps-deploy-amazon-q.yaml
--- a/cicd/templates/steps-deploy-amazon-q.yaml
+++ b/cicd/templates/steps-deploy-amazon-q.yaml
@@ -7,6 +7,24 @@ steps:
     targetType: 'inline'
     script: |
       set -euxo pipefail
+      
+      # Check if AWS CLI is installed
+      if ! command -v aws &> /dev/null
+      then
+          echo "AWS CLI could not be found"
+          exit 1
+      fi
+
+      # Check AWS CLI version
+      aws_version=$(aws --version)
+      echo "AWS CLI version: $aws_version"
+
+      # Check if necessary variables are set
+      if [ -z "$serviceName" ] || [ -z "$identityCenterInstanceARN" ] || [ -z "$amazon-q-roleARN" ]; then
+        echo "One or more required variables are not set"
+        exit 1
+      fi
+
       output=$(aws qbusiness create-application --display-name "$(serviceName)" --identity-center-instance-arn "$(identityCenterInstanceARN)" --role-arn "$(amazon-q-roleARN)" --description "Amazon Q Chatbot")
       applicationId=$(echo $output | jq -r '.applicationId')
       echo "##vso[task.setvariable variable=application_Id;isOutput=true]$applicationId"
@@ -14,6 +32,7 @@ steps:
       echo "application_Id: $(application_Id)"
   name: createApplication
 
+  
 # - task: AWSCLI@1
 #   displayName: 'Create Application'
 #   inputs:
